### ISSUE TITLE
Build sources

### ISSUE THREAD

**Issue by tsamaya** [muxlab/map-effects-100#14]
Hi MuxLab team,

I think using something like gulp-processhtml can help us during development using gulp with linting and build source automaticcaly in a destination folder

https://www.npmjs.com/package/gulp-processhtml

My thoughts: 
- move sources files into a src folder (js and html)
- add gulp plugins
- build project source with destination in [leaflet](/muxlab/map-effects-100/tree/gh-pages/Leaflet) folder 
- update [CONTRIBUTING.md](/muxlab/map-effects-100/blob/gh-pages/CONTRIBUTING.md)

**Comment by ynunokawa** [comment]
**WAKUWAKU**:smile: (it means waiting for fun in Japanese!)

I am surprised your continual work.

**Comment by tsamaya** [comment]
it is almost done ! I had to test it completely before PR :smile:

**Comment by ynunokawa** [comment]
@tsamaya Great!
By the way, can I commit to add new one effect? If your testing is finished and PR comes soon, I will do after it. :octocat:

**Comment by tsamaya** [comment]
just in time I send you the PR

2015-12-15 15:45 GMT+01:00 Yusuke Nunokawa notifications@github.com:
